### PR TITLE
downgrade sauce labs firefox browser version to the 46

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @georgiy-abbasov 
for more details see https://github.com/DevExpress/testcafe-hammerhead/pull/648#issuecomment-229645456

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
