### PR TITLE
update browser matrix to latest ios versions

### PR DESCRIPTION
**Pull request by miherlosev**
@AlexanderMoskovkin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@AlexanderMoskovkin .

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov please investigate this

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, @miherlosev
Sauce Labs platform configurator recommends to use this options to launch VM correctly. 
```js
caps['browserName'] = 'Safari';
caps['appiumVersion'] = '1.5.3';
caps['deviceName'] = 'iPhone 6 Plus';
caps['deviceOrientation'] = 'portrait';
caps['platformVersion'] = '9.3';
caps['platformName'] = 'iOS';
```
At the current moment most of these settings doesn't pass while configuring SL job on our side([qunit-harness](https://github.com/AlexanderMoskovkin/qunit-harness/)), so we should extend it first (i'll do this).

**Comment by AlexanderMoskovkin** [comment]
Why does it work for ios 9.2? We should not extend all of options. We should find the exactly reason why it doesn't work with `9.3`.

**Comment by AlexanderMoskovkin** [comment]
@miherlosev I suppose 
```json
 {
        browserName: 'iphone',
        platform:    'OS X 10.10',
        version:     '9.3',
        deviceName:  'iPhone 6 Plus'
    }
```
is just a restricted combination. Please try as saucelabs configurator recommends:
```json
 {
        browserName: 'iphone',
        platform:    'iOS',
        version:     '9.3',
        deviceName:  'iPhone 6 Plus'
    }
```
If it doesn't work we will investigate this in `qunit-harness`

**Comment by miherlosev** [comment]
I have changed the sauce labs setting for latest ios version as you described.
The error is reproduced.
Investigate it.

**Comment by AlexanderMoskovkin** [comment]
Yes, I see. @georgiy-abbasov will take care about this

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov `qunit-harness@0.3.6` just published. Please, write how @miherlosev should configure the task

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
ping @AlexanderMoskovkin

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Problem with npm.
```
npm ERR! fetch failed https://registry.npmjs.org/multiline/-/multiline-1.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
```
I found the related issue https://github.com/npm/npm/issues/13286
Waiting for resolution

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR
@AlexanderMoskovkin
After merge do this in `testcafe` repository.

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
