### PR TITLE
fix `Wrong CORS emulation for 'fetch' requests` (close #1059)

### LINKED ISSUE #1059: Wrong CORS emulation for 'fetch' requests
We don't send the `origin` header to the origin site.
See https://github.com/DevExpress/testcafe/issues/1134#issuecomment-285694901

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
So the initial problem was only with `fetch` requests or what?

**Comment by LavrovArtem** [comment]
@inikulin yes, only with `fetch` requests. All works great with `xhr` requests.

**Comment by inikulin** [comment]
@LavrovArtem Can we change titles for issue and PR then?

**Comment by LavrovArtem** [comment]
@inikulin yes of course

**Comment by LavrovArtem** [comment]
ping @churkin

**Pull request merged**
