### PR TITLE
fix wrong event name (close #634)

### LINKED ISSUE #634: Typo in hammerhead.EVENTS
There should be `unload` instead of `upload`.
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/index.js#L34

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @georgiy-abbasov

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
This wrong field was not used nowhere. I propose to don't increment the major version here

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by miherlosev** [comment]
I removed the major version increment.
So, FPR

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by miherlosev** [comment]
@churkin is absent. @AlexanderMoskovkin review please

**Comment by AlexanderMoskovkin** [comment]
@miherlosev I suppose we should update minor or patch version to publish the fix we the new release. Are you agree?

**Comment by miherlosev** [comment]
Ok.I updated the patch version.

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
please, publish this

**Comment by miherlosev** [comment]
> please, publish this

Done

**Pull request merged**
