### PR TITLE
try to stabilize the blinking test (close #1202)

### LINKED ISSUE #1202: Stabilize the blinking test
`SVG elements\' className is of the SVGAnimatedString type instead of string (GH-354)`
C:\Hammerhead_github\test\client\fixtures\sandbox\shadow-ui-test.js

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
If the shadowUI root exists and we call `setProperty(document.body, 'innerHTML', '<svg></svg>' + document.body.innerHTML);` then we have two shadowUI roots (two elements with the same id, but only one marked as shadow element). 
Need to more strictly handle this case:  
- after getting the shadowUI need to check count of root
- if their count equals two then need to clone all children from previous root to the new
- after we need to remove old root and mark the new root as shadow element

**Comment by miherlosev** [comment]
Waiting for green tests

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Pull request merged**
