### PR TITLE
fix `A class that extends `Function` is not getting the correct prototype when running under Hammerhead` (close #2439)

### LINKED ISSUE #2439: A class that extends `Function` is not getting the correct prototype when running under Hammerhead
### What is the Current behavior?
A class that extends `Function` is not getting the correct prototype.

To reproduce, create a minimal app that executes the following:
 
```js
class Test extends Function {
	extend() {}
}
console.log(new Test().__proto__);
 
```

Running it in Chrome shows the following in dev tools:

image

When running under Testcafe, the following is shown:
image

In Testcafe, instantiated classes that extend `Function` no longer have access to their methods. Presumably this is due to the native `Function` [being overwritten](https://github.com/DevExpress/testcafe-hammerhead/blob/f7c0cc4cc53fa4fbc0c05fe7ae9801d4c330576c/src/client/sandbox/node/window.ts#L726-L728) but I didn't do much other digging once I could create a test case.

### Your Environment details:

* node.js version:                    v14.4.0
* browser name and version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
* platform and version:          Observed on OSX and Windows

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \restart

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \restart

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \restart

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \restart

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \restart

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \restart

**Review by miherlosev — APPROVED** [review]

**Review by Farfurix — APPROVED** [review]

**Pull request merged**
