### PR TITLE
use native util.promisify

### PR DESCRIPTION
**Pull request by miherlosev**
@LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
Remove `pify` from `package.json`

**Comment by miherlosev** [comment]
@LavrovArtem FPR

**Pull request merged**
