### PR TITLE
remove domProcessor.processElement from NodeSandbox._processElement(close #494)

### LINKED ISSUE #494: Try to get rid domProcessor.processElement from NodeSandbox._processElement

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
