### PR TITLE
Added the ability to set outside proxy url (close #1032)

### LINKED ISSUE #1032: Add the ability to set outside proxy url

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @georgiy-abbasov

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
It works with sniffer proxy, awesome!
But it seems to me, that we should have ability to set external proxy settings via Hammerhead ctor - [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/proxy/index.js#L25). @churkin, what do you think ?

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Pull request merged**
