### PR TITLE
Simulation of touch events fixed for new Chrome version (closes #927)

### LINKED ISSUE #927: We should support simulation of touch events for new Chrome version
Chrome 54 has changed method of creation touch events, so we should support it.

### PR DESCRIPTION
**Pull request by helen-dikareva**
Require to fix TestCafe issue https://github.com/DevExpress/testcafe/issues/944
Existent qunit tests are enough to check fix
/cc @AlexanderMoskovkin @churkin

### CODE REVIEW

**Comment by helen-dikareva** [comment]
@testcafe-build-bot  \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
Wait for https://github.com/DevExpress/testcafe-hammerhead/pull/919 and fix tests in TestCafe

**Comment by AlexanderMoskovkin** [comment]
BTW: @helen-dikareva please create an issue for this PR and add it in the Sprint#2 milestone

**Comment by helen-dikareva** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/927

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
FPR

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Pull request merged**
