### PR TITLE
fix 'domUtils.isIframeWithoutSrc returns wrong result after documentopen in same-domain iframe' (close #703)

### LINKED ISSUE #703: domUtils.isIframeWithoutSrc returns wrong result after document.open in same-domain iframe
see test for reproduce:
```javascript
var iframe  = document.createElement('iframe');

iframe.src = <same-domain-url>
iframe.id = 'test_unique_id';
    window.QUnitGlobals.waitForIframe(iframe)
        .then(function () {
            var result = domUtils.isIframeWithoutSrc(iframe);
            ok(!result);

            iframe.contentDocument.open();

            result = domUtils.isIframeWithoutSrc(iframe); // result equal 'true'. It is wrong

            iframe.parentNode.removeChild(iframe);
            start();
        });
document.body.appendChild(iframe);
});
```

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by miherlosev** [comment]
I checked the following iframe types:
1. iframe with cross-domain src.
2. iframe with same-domain src.
3. iframe with about:blank
4. iframe with empty src.
5. iframe without src attribute.
6. iframe with not supported protocol (javascript protocol).

I don't find case then iframe without src has document.location as top window with src.
So, FPR

**Comment by churkin** [comment]
lgtm

**Pull request merged**
