### PR TITLE
Make active-window-tracker Qunit tests stable (close #282)

### LINKED ISSUE #282: Make active-window-tracker Qunit tests stable

### PR DESCRIPTION
**Pull request by helen-dikareva**
Wait for tests' stability before review

### CODE REVIEW

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
It seems the PR fixes the problem with unstable `activeWindowTracker` tests. But we have a strange issue in IE9. Different tests were failed in different test runs with the same error:
```
Windows 7 internet explorer 9.0 - /fixtures/utils/html-test.js
Test: real big page
message: Test timed out
```
```
Windows 7 internet explorer 9.0 - /fixtures/sandbox/event/event-test.js
Test: focus / blur events in iframe (B253685)
message: Test timed out
```
```
Windows 7 internet explorer 9.0 - /fixtures/sandbox/node/methods-test.js
Test: script must be executed after it is added to head tag (B237231)
message: Test timed out
```
```
Windows 7 internet explorer 9.0 - /fixtures/sandbox/event/active-window-tracker-test.js
Test: check switching active window (between two iframes)
message: Test timed out
```

The `timeout` value for qunit tests is `30000ms`, but tests fail within a few milliseconds (30-300) after the start. I'll research this

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
`active-tracker-window` tests are ok with this PR. I suppose we can review it 
/cc @inikulin @churkin

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
