### PR TITLE
fix Firefox strange behavior

### PR DESCRIPTION
**Pull request by churkin**
\сс @AlexanderMoskovkin @inikulin @AndreyBelym

### CODE REVIEW

**Comment by AndreyBelym** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
Regression test?
\r-

**Comment by churkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm

**Pull request merged**
