### PR TITLE
Add fix for crossing shadow boundary in getParents()

### PR DESCRIPTION
**Pull request by varunkumar**
Add fix for scrolling elements inside ShadowDOM. https://github.com/DevExpress/testcafe/issues/1808

### CODE REVIEW

**Comment by miherlosev** [comment]
I've checked your PR and found out that it does not completely fix the related TestCafe's issue.

If you run the following test code against your PR, it will fail.
```js
test('"getParents" should work properly for elements inside shadowDOM', function () {
    var host  = document.createElement('div');
    var root  = host.createShadowRoot();
    var input = document.createElement('input');

    document.body.appendChild(host);
    root.appendChild(input);

    var parents = domUtils.getParents(input);

    deepEqual(parents, [root, host, document.body, document.documentElement]);
   document.body.removeChild(host);
});
```

It happens because we check that element's parent is `ELEMENT_NODE` (see https://github.com/DevExpress/testcafe-hammerhead/blob/e0e9e8c4d2ca600183282ef9ca41becbf4c758b2/src/client/utils/dom.js#L747)
But element's parent is `DOCUMENT_FRAGMENT_NODE`.
Also we should work properly with document fragment nodes that are not in shadowDOM.

**Comment by AlexanderMoskovkin** [comment]
Guys, since the `getParents` function became more complex please add a simple qunit test for the ShadowDOM case

**Comment by miherlosev** [comment]
Guys, we will improve this functionality in context of support web components.

**Comment by varunkumar** [comment]
Is there any timeline for this? We use `web-components` heavily and having a full fledged support from TestCafe would be helpful.

**Comment by miherlosev** [comment]
We are planning to start working with your PR next week.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR
@LavrovArtem @AndreyBelym

**Comment by miherlosev** [comment]
ping @LavrovArtem @AndreyBelym

**Pull request merged**
