### PR TITLE
[WIP]Add special url flag for the authentication via social networks in iframe

### PR DESCRIPTION
**Pull request by LavrovArtem**
related with https://github.com/DevExpress/testcafe-hammerhead/issues/1428

### CODE REVIEW

**Comment by LavrovArtem** [comment]
This PR is unnecassary because the `x-frame-options` header can be replaced via the [Request Hooks](https://github.com/DevExpress/testcafe/pull/2200) feature.

**Comment by gbatz** [comment]
Hi @LavrovArtem 
Could you please share how exactly can the `x-frame-options` header be replaced via Request Hooks?
I implemented the hook, it fires up for my specific request, but still that header seems to be unaffected.
I'm using your workaround for Facebook Login popup. Setting the `'x-frame-options': skip`, in `header-transforms` works good, but I don't want to keep locally that change in `node_modules`.
Thanks!

**Comment by LavrovArtem** [comment]
Hi @gbatz,
For your scenario, you should use the `_onConfigureResponse` method. Unfortunately, it is not documented. The event object has the `setHeader (name, value)` and `removeHeader (name)` methods. For example:

```js
class MyRequestHook extends RequestHook {
    constructor (requestFilterRules, responseEventConfigureOpts) {
        super(requestFilterRules, responseEventConfigureOpts);
    }
    onRequest (event) {
    }
    onResponse (event) {
    }
    _onConfigureResponse (event) {
        event.removeHeader('x-frame-options');
    }
}
```

**Comment by gbatz** [comment]
Thanks @LavrovArtem for your quick response! That worked like a charm!
I can only hope, still, that new window popups will be supported by testcafe in the near future. There's still lots of other pain with this.
Thanks for your hard work!

**Pull request closed without merging**
