### PR TITLE
fix 'Operator 'instanceof' wrong work with Blob class' (close #690)

### LINKED ISSUE #690: Operator 'instanceof' wrong work with Blob  class
Test code from http://html5test.com
```javascript
var b = new Blob();
b instanceof Blob;
> false
```
Also we need to check all overriden constructors (Image, Worker, FontFace, etc)

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by miherlosev** [comment]
@LavrovArtem review please

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
