### PR TITLE
Revert "Methods that returns live node collection fixed (closes #1096…

### LINKED ISSUE #1096: Wrong proxing methods that returns live node collection
Reproduced in playrground. Relates to https://github.com/DevExpress/testcafe/issues/1442

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
…) (#1103)"

This reverts commit 885436e6090d968e5c44ac7cb2deae9765865be5.

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
Client tests are [ok](https://www.screencast.com/t/54eoZYyzGwRH), there is just problem with starting chrome beta on windows 10, which doesn't relate to PR
\cc @churkin

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Pull request merged**
