### PR TITLE
[WIP] cache the node_modules folder

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by inikulin** [comment]
@AlexanderMoskovkin How it works?

**Comment by inikulin** [comment]
@AlexanderMoskovkin I mean is it some kind of smart cache? Because it would be nice to know from CI if some minor dependency update broke something

**Comment by AlexanderMoskovkin** [comment]
@inikulin I haven't found the answer for this question in travis docs. Therefore I don't know yet can we use this approach or not.

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@AlexanderMoskovkin They have a github repo, maybe it makes sense to ask them there?

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
It's not a kind of smart caching. It just [caches](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/164917276#L1162) the `node_modules` directory when the `npm test` command done. When the task is started it [tries to find](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/164917276#L146) cached directory by branch name (the current branch or master branch).

So, we should NOT use this caching for master branch. Because we should run our tests with actual dependencies. 
But Build-Bot can use it for pull-requests. It will make faster repeated tests. It will work in the following way:
1) You create a pull-request
2) Build-bot creates a branch with your changes and trigger the tests
3) Travis can't find cached `node_modules` directory for this branch (because it's the first tests run for this branch). Dependencies will be installed via npm and cached when the tests are done.
4) If you restart the tests or push an additional commit travis gets the cached directory for this branch.

Note, if you change some dependencies in the package.json in your additional commit, you have to clear travis cache manually via UI.

So, what do you think should we do this in build bot.

**Comment by inikulin** [comment]
@AlexanderMoskovkin Overall, it sounds good, except:

> Note, if you change some dependencies in the package.json in your additional commit, you have to clear travis cache manually via UI.

Unfortunately it's blocking us from switching to this feature.

**Comment by AlexanderMoskovkin** [comment]
@inikulin Yes, I'm agree.

**Pull request closed without merging**
