### PR TITLE
Use `iltorb` module instead of 'brotli`

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @miherlosev @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
let's test it on health-monitor before merging

**Comment by miherlosev** [comment]
> let's test it on health-monitor before merging

Yes, we discussed in private this.
Also, please provide information about:
- decode/encode large file (about 1Mb) with old and new library and provide speed and memory usage comparison
- measure memory allocation on library initialization
- encode

**Comment by LavrovArtem** [comment]
Size of the source hammerhead.js file is 1mb.

| | brotli | iltorb
--- | ---: | ---:
encoding time | 5100ms | 2400ms
size after encoding | 531kb | 149kb
decoding time | 35ms | 5ms
memory allocation on library initialization | 310mb | 2.5mb
memory usage | 315mb | 4.1mb

**Comment by miherlosev** [comment]
Two health monitor runs:
https://testcafe-hhhm.devexpress.com/history?timestamp=1505311354244
https://testcafe-hhhm.devexpress.com/history?timestamp=1505333732609

The `itorb` module is faster and requires less memory on module initialization and during decoding/encoding.
There is no new probles or performance degradation.

So, there is no reasons to don't merge it.
/cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
awesome!

**Pull request merged**
