### PR TITLE
fix 'native methods of the iframe document aren't overridden for iframe with javascript src' (close #358)

### LINKED ISSUE #358: native methods of the iframe document aren't overridden for iframe with javascript src
Found in:
http://www.about.com/
http://www.alibaba.com/
etc.
Example
```javascript
    var iframe            = document.createElement('iframe');

    iframe.id = 'test_nmsghf';
    iframe.setAttribute('src', 'javascript:"<html><body>test</body></html>"');
    iframe.addEventListener('load', function () {
        var iframeHammerhead    = iframe.contentWindow['%hammerhead%'];
        var iframeNativeMethods = iframeHammerhead.nativeMethods;

        ok(iframeNativeMethods.createElement.toString().indexOf('native code') !== -1);
    });

    document.body.appendChild(iframe);
```
On the second `load event` `iframeNativeMethods.createElement` contains overriden value instead of native.

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by miherlosev** [comment]
So, after discuss with @churkin I performed a some changes in IframeSandbox.
FPR.

**Comment by inikulin** [comment]
ping @churkin @LavrovArtem

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
