### PR TITLE
FormData.prototype.append must be overridden (close #324)

### LINKED ISSUE #324: FormData.prototype.append must be overridden
If we append our file wrapper to ```FormData```, we will lose the file name. And we should not send our hidden input's value along with the file info, because our input may have incorrect value if the input with the file has been removed from DOM.

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by miherlosev** [comment]
lgtm

**Pull request merged**
