### PR TITLE
Performance improvements (properties instrumentation)

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
run monitor

**Comment by LavrovArtem** [comment]
run monitor

**Comment by LavrovArtem** [comment]
run monitor

**Comment by LavrovArtem** [comment]
run monitor

**Comment by LavrovArtem** [comment]
run monitor

**Comment by LavrovArtem** [comment]
run monitor

**Comment by LavrovArtem** [comment]
run monitor

**Review by miherlosev — APPROVED** [review]

**Pull request merged**
