### PR TITLE
AttributesWrapper is synchronizing with actual element attributes for now (closes #924)

### LINKED ISSUE #924: [todomvc] Browser hangs on the Riot.js demo page opening
page: http://todomvc.com/examples/riotjs/

reproduced in playground. Tested in Chrome but should be checked in other browsers

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin, @churkin, @miherlosev

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR. Some remarks, which were discussed in private with @churkin, are fixed.

**Comment by georgiy-abbasov** [comment]
Sorry, i have found a mistake, i'll push a fix.

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
@churkin Please review it again with the last changes

**Pull request merged**
