### PR TITLE
fix `Focusing element inside shadow dom not working` (close #2408)

### LINKED ISSUE #2408: Focusing element inside shadow dom not working
### What is your Test Scenario?
Application code calls focus() method on an element inside shadow dom. Test code tries to verify the element inside shadow dom is in focus.
 
### What is the Current behavior?
Native focus method is not called when the focus method is called from application for an element inside shadow dom. Testcafe considers the element is not visible and doesn't trigger the native focus method. 
Probably because https://github.com/DevExpress/testcafe-hammerhead/blob/f68857f899c538b3ee054be75a1166fe5b1dcf1e/src/client/sandbox/event/focus-blur.ts#L273 think the element is invisible

https://github.com/DevExpress/testcafe-hammerhead/blob/4789241f9f93d43923fd892a74b4d4786b5e79d2/src/client/utils/style.ts#L329

### What is the Expected behavior?
Native focus method should be triggered if the element is inside shadow dom.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

```js
const button = document.querySelector('custom-element').shadowRoot.querySelector('.close--button');
button.focus();
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 await t.expect(Selector(() => {
    // @ts-ignore
    let activeElement = document.activeElement || document.body;
    
    while(activeElement && activeElement.shadowRoot) {
      const currentElement = activeElement.shadowRoot.activeElement;

      if (!currentElement) {
        break;
      }
      activeElement = currentElement;
    }
    return activeElement;
  }).hasClass('close--button')).ok();
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    12.13.0
* command-line arguments:  
* browser name and version: Chrome 80
* platform and version:          macOS 10.14.6
* other:

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Review by miherlosev — APPROVED** [review]

**Review by Farfurix — APPROVED** [review]

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
[testcafe-hammerhead-19.1.0.zip](https://github.com/DevExpress/testcafe-hammerhead/files/5802144/testcafe-hammerhead-19.1.0.zip)

**Comment by LavrovArtem** [comment]
[testcafe-hammerhead-19.1.0.zip](https://github.com/DevExpress/testcafe-hammerhead/files/5812832/testcafe-hammerhead-19.1.0.zip)

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Pull request merged**
