### PR TITLE
Active-window-tracker raises error when try to check removed iframe's window.top property (close #271)

### LINKED ISSUE #271: Active-window-tracker raises error when try to check removed iframe's window.top property
We don't need check ```if (this.activeWindow !== this.activeWindow.top)``` after receive WINDOW_ACTIVATED_EVENT

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @inikulin @churkin 
test name was checked

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
tests fail

**Comment by inikulin** [comment]
@helen-dikareva @churkin We need to release v2.0.1?

**Comment by churkin** [comment]
@inikulin Yes

**Comment by churkin** [comment]
I do it

**Pull request merged**
