### PR TITLE
try to stabilize tests: part 1 - increase timeout for waitForIframe

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Ok. Now tests are green. I will run tests a several days.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
In this pull request we have 2 builds that failed by timeout error. Full build count - 14.
So the percentage of false positives 2 / 14 = 0.14 - 14%

And I checked percenge of false positives for latest opened pull requests:
#842 - 2/5 = 0.4 (40 %).
#809 - 11 / 15 = 0.73 (73%)
#781 - 4 / 7 = 0.57 (57%).

So timeout increasing for `waitForIframe` is decreased the false positives percent.
@churkin @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
> we have 2 builds that failed by timeout error

Are this failures related to iframe loading issue?

**Comment by miherlosev** [comment]
> Are this failures related to iframe loading issue?

No, it is iframe timeout error on mobile emulators (ios and android)
see builds: 
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/165761387
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/165738173

**Pull request merged**
