### PR TITLE
fix `fetch.toString() prints full function code instead of function fetch() { [native code] }` (close #1662)

### LINKED ISSUE #1662: is:issue is:open fetch.toString() prints full function code instead of function fetch() { [native code] }
I am testing an app that stores data to indexedDB via [localForage](https://github.com/localForage/localForage)

When testing on iOS (11.4) localForage fails to recognize indexedDB and falls back to other storage drivers. Besides other conditions it checks for the availability of fetch like so: `fetch.toString().indexOf('[native code') !== -1`

This condition returns `true` when running the app on iOS directly but fails when remote testing the app on iOS via testcafe, because `fetch.toString()` prints the whole function code instead of `function fetch() { [native code] }` as expected from any browser.

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1662

localForage/src/utils/isIndexedDBValid.js
https://github.com/localForage/localForage/blob/55db1ef633af28abe98ea0baf68fa1c24566f282/src/utils/isIndexedDBValid.js#L20-L22

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
Don't retest. The problem was found in `qunit-harness` module.

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Pull request merged**
