### PR TITLE
domUtils.isTextEditableInput is fixed (closes  #1049)

### LINKED ISSUE #1049: Exclude "datetime" from "isTextEditableInput" DOM util
This is necessary to allow type automation on this type (https://github.com/DevExpress/testcafe/issues/1258)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @churkin, @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by georgiy-abbasov** [comment]
I need some time to check, that it's needed, not actual at this moment

**Comment by georgiy-abbasov** [comment]
FPR

**Pull request merged**
