### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by miherlosev**
1)add `domUtils.isElementNode`, `domUtils.isDocumentNode`, etc. 
2)remove unused code from `NodeSandbox.overrideDomMethods`.
3)add `getNativeQuerySelectorAll ` method
4)add tests for HiddenInfo changing (add / remove different element types).

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR.
/cc @churkin @AlexanderMoskovkin

**Comment by churkin** [comment]
\r-

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

some API functions were added to `domUtils`. I suppose we should update the version (increase `minor` number) and publish it.

**Pull request merged**
