### PR TITLE
Bump version to 10.6.3

### PR DESCRIPTION
**Pull request by churkin**
/cc @miherlosev

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
see https://github.com/DevExpress/testcafe-hammerhead/issues/1076

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Rebase and retest

**Pull request merged**
