### PR TITLE
fix 'Node.replaceChild doesn't handle file input elements' (close #399)

### LINKED ISSUE #399: Node.replaceChild doesn't handle file input elements
You can request upload for a file input, and the replace  it with another input with help of [Node.replaceChild](https://developer.mozilla.org/ru/docs/Web/API/Node.replaceChild) before submitting. In that case a value of the second input must be submitted, but hammerhead submits file selected in the first input. So we need to override replaceChild for file inputs just the way we are overriding Node.appendChild and Node.removeChild.

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @AndreyBelym

### CODE REVIEW

**Comment by churkin** [comment]
test?

**Comment by miherlosev** [comment]
I don't know how to create a test because we cannot setup value for `input` with `type=file` on client side.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Waiting for #277

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
ping @churkin @AndreyBelym

**Comment by miherlosev** [comment]
According the browser security restrictions, we cannot setup value for `input` with `type=file` on client side.
So, to create the client test we need to mock the following methods:
`domUtils.isDomElement`
`domUtils.isFileInput`
`UploadSandbox._getCurrentInfoManager`
`UploadSandbox.getFiles`
`getSandboxBackup`

It have made test very large and difficult.
What do you think?
@churkin @AlexanderMoskovkin

**Comment by churkin** [comment]
@AlexanderMoskovkin Can be replaced by a testcafe functional test, i think.

**Comment by miherlosev** [comment]
We decide to create separate tests for it. see https://github.com/DevExpress/testcafe/issues/293#issuecomment-181312367
So, FPR

**Comment by AndreyBelym** [comment]
lgtm. I think there is a problem with a test because the PR adds functionality in `node` sandbox, but it's also heavily depends on `upload` sandbox. It means that we need to test both sandboxes in the same time. So can we create a test for upload sandbox, like test [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/upload-test.js), but also connect the `node` sandbox?

**Comment by miherlosev** [comment]
>> I think there is a problem with a test because the PR adds functionality in node sandbox, but it's also heavily depends on upload sandbox. It means that we need to test both sandboxes in the same time.

I don't see problem in this place. All `upload` subsistems are tested in [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/upload-test.js).
We cannot write the integration qunit test (see [here] (https://github.com/DevExpress/testcafe-hammerhead/pull/403#issuecomment-181299735)).

This is why we will create intergration functional tests

**Comment by miherlosev** [comment]
ping @churkin

**Comment by churkin** [comment]
lgtm

**Pull request merged**
