### PR TITLE
Our iframe-task.js comes to an advertising iframe with status 500 because it doesn't have the referer header (close #377)

### LINKED ISSUE #377: Our iframe-task.js comes to an advertising iframe with status 500 because it doesn't have the referer header
* http://66.55.147.18:13500/history?timestamp=1453883877849&siteUrl=http://kakaku.com/
* http://66.55.147.18:13500/history?timestamp=1453883877849&siteUrl=http://www.milliyet.com.tr/

### PR DESCRIPTION
**Pull request by churkin**
\cc @LavrovArtem @kirovboris

### CODE REVIEW

**Comment by kirovboris** [comment]
Tests failed. Please fix it.

**Comment by churkin** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Pull request merged**
