### PR TITLE
Raise an event when the page is really going to be unloaded (#667). Part 2 - links.

### PR DESCRIPTION
**Pull request by churkin**
\cc @AlexanderMoskovkin @LavrovArtem

### CODE REVIEW

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
