### PR TITLE
Update to v.2.0.1

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm, don't forget about git tag

**Comment by inikulin** [comment]
Fail in active window tracker looks not accidental. \cc @helen-dikareva

**Comment by helen-dikareva** [comment]
Ok, I'll see

**Comment by helen-dikareva** [comment]
I could not reproduce test failure locally on MacBook's iPhone simulator and with manually created virtual machine on SauceLabs. So tests deserve another chance.
sauce_tunnel
sauce_tunnel2

**Comment by inikulin** [comment]
@helen-dikareva However, there are still fails that involves active window tracker. Seems like some timing issue, which reproduces only on slow machines.

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
