### PR TITLE
Speeding-up domUtils.isDomElement function (part of #424)

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @AlexanderMoskovkin @LavrovArtem 
see http://jsperf.com/speed-up-isdomelement-function/4

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
waiting for https://github.com/DevExpress/testcafe-hammerhead/issues/431

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
