### PR TITLE
fetch barrier (part of #498)

### PR DESCRIPTION
**Pull request by miherlosev**
Pull request contains two part of code - for hammerhead and for testcafe.
Code for hammerhead  - event `FETCH_REQUEST_SEND_EVENT`.
Code for testcafe - `fetchBarrier` implementation and tests.

Review it in the single pull request.
After it I will close this pull request and create two separate pull request - one for hammerhead and another for testcafe.

@inikulin @churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
