### PR TITLE
Expose `isScriptProcessed` method, rename `wrapDomAcessors` to `processScript`. Fix line endings in script test. Bump version (closes #600)

### LINKED ISSUE #600: Expose `isScriptProcessed` method, rename `wrapDomAcessors` to `processScript`
Required for https://github.com/DevExpress/testcafe/issues/524

### PR DESCRIPTION
**Pull request by inikulin**
\cc @churkin @miherlosev

### CODE REVIEW

**Comment by churkin** [comment]
lgtm

**Comment by miherlosev** [comment]
lgtm

**Comment by inikulin** [comment]
Guys can you publish this ASAP?

**Comment by miherlosev** [comment]
Already published - https://github.com/DevExpress/testcafe-hammerhead/releases/tag/v9.0.0

**Pull request merged**
