### PR TITLE
remove unused code (it was moved to FocusBlur sandbox)

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @LavrovArtem 
see [here] (https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/focus-blur.js#L334)

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
