### PR TITLE
All types of the 'postMessage' function calls wrapped (close #759)

### LINKED ISSUE #759: Script error for http://www.semrush.com/
see [video](http://screencast.com/t/6EJAgYIS)

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@LavrovArtem  I believe it's a problem with implementation, not a regular test instability.

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
@miherlosev  separate issue https://github.com/DevExpress/testcafe-hammerhead/issues/834

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
ping @churkin

**Pull request merged**
