### PR TITLE
uuid replaced with shortid (closes #484)

### LINKED ISSUE #484: 'uuid' generates the same id for different sessions sometimes
Our TestCafe functional tests sometimes fail with a strange error (rarely but regularly). @georgiy-abbasov have found it happens because `hammerhead` sets identical ids for different sessions [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/session/index.js#L32) ([proof](http://screencast.com/t/GlTNsseXCRF))

We should do something with this. We can just add some symbols to session id or use some more specific logic
/cc @inikulin @churkin @georgiy-abbasov

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @churkin, @AlexanderMoskovkin

### CODE REVIEW

**Comment by churkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
@churkin please publish this with `patch` version number updating

**Comment by AlexanderMoskovkin** [comment]
oops. It's my mistake. I've just closed the PR and haven't merge it. I'll merge it when tests are completed

**Pull request merged**
