### PR TITLE
fix 'Script error for 'window.Worker' in IE9' (close #706)

### LINKED ISSUE #706: Script error for 'window.Worker' in IE9
IE9 hasn't `window.Worker` property.

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by churkin** [comment]
lgtm

**Comment by miherlosev** [comment]
@LavrovArtem review this pull request, please

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
