### PR TITLE
Infinite 'set-cookie' service messages on http://www.alibaba.com/ (close #492)

### LINKED ISSUE #492: Infinite 'set-cookie' service messages on http://www.alibaba.com/
Open site in playground and switch to  Network Tab in the Browser console.

### PR DESCRIPTION
**Pull request by churkin**
\сс @AlexanderMoskovkin @miherlosev

### CODE REVIEW

**Comment by inikulin** [comment]
There is a problem with line endings

**Comment by churkin** [comment]
@inikulin I have fixed to the correct (LF)

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by miherlosev** [comment]
lgtm

**Pull request merged**
