### PR TITLE
change the first character of the test name to lowercase (close #298)

### LINKED ISSUE #298: QUnit test names must start with lowercase
In many places our qunit test names start with uppercase.
For example:
https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/shadow-ui-test.js#L577
https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/xhr-test.js#42
https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/node/dom-processor-test.js#365
etc.
Need to change their to lowercase.

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @inikulin @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Comment by churkin** [comment]
check tests pls

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Pull request merged**
