### PR TITLE
use unminified hammerhead version for playground

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@miherlosev We can use dev option for tests also.

**Comment by miherlosev** [comment]
Later we discussing this theme and decide to run tests on the final version of the code - on minified version.
It needs to prevent problems with minifed tool.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR @churkin

**Pull request merged**
