### PR TITLE
Get rid of unhandled rejection on `about:blank` requests. Fix stale `about:blank` requests for non-processable resources (fixes #796)

### LINKED ISSUE #796: [Testing day 0.9.0-rc1] Unhandled rejection then navigate to special page
see more details in https://github.com/DevExpress/testcafe/issues/817

### PR DESCRIPTION
**Pull request by inikulin**
\cc @miherlosev @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@churkin @miherlosev @LavrovArtem WTF is going on with your client tests, guys?

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@inikulin 
All failed tests uses content that loaded via iframe with src.
Due to network problems these error are reproduced.

**Pull request merged**
