### PR TITLE
add test case for T388558 bug

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
is the bug was fixed before?

**Comment by churkin** [comment]
lgtm

**Comment by miherlosev** [comment]
> is the bug was fixed before?

Bug presents in 15.2.latest. Version 15.2.latest uses the old `acorn` parser - 0.4.1.

The github version uses the latest `acorn` version. And in github version bug don't present.
We decide to add test case from T388558 to the hammerhead github version.

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
