### PR TITLE
Multiple errors for document.write tests (close #632)

### LINKED ISSUE #632: Multiple errors for document.write tests
Steps to reproduce:
1)Open https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/node/document-write-test.js
2)After each `write` or `writeln` statement one setup the comparison the native document write result and our write result. See code snippet below:
```javascript
function getDocumentOuterHtml (iframe) {
    return iframe.contentDocument.documentElement.outerHTML;
}

function checkWriteResults () {
    strictEqual(getDocumentOuterHtml(iframeForWrite), getDocumentOuterHtml(iframeForNativeWrite));
}

test('write script', function () {
      write('<script>');
      checkWriteResults();

      write('var x = 5;');
      checkWriteResults();

//etc. Perform this for all write and writeln calls in all tests
});
```
3)You will get a lot of assertion errors.

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

**Comment by miherlosev** [comment]
lgtm

**Comment by LavrovArtem** [comment]
ping @churkin

**Comment by LavrovArtem** [comment]
ping @churkin

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
Guys, please give sane names to PRs. If you fix something add `Fix` prefix. For now it looks like you just committed multiple errors for document.write tests

@DevExpress/testcafe

**Pull request merged**
