### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin

### CODE REVIEW

**Comment by miherlosev** [comment]
Waiting for https://github.com/DevExpress/testcafe-hammerhead/issues/1222

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Pull request merged**
