### PR TITLE
fix 'Script errors for http://www.quikr.com' (close #669)

### LINKED ISSUE #669: Script errors for http://www.quikr.com/
Possible regression from https://github.com/DevExpress/testcafe-hammerhead/commit/8bf0072371fb1b4e3572634db0380c4ad5caa88e

Stack trace

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by LavrovArtem** [comment]
lgtm

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Pull request merged**
