### PR TITLE
fix 'Script error for http://www.wp.pl' (close #666)

### LINKED ISSUE #666: Script error for http://www.wp.pl
see https://testcafe-hhhm.devexpress.com/history?timestamp=1467918418380&siteUrl=http://www.wp.pl/

Stack trace:
```javascript
hammerhead.js:11221 Uncaught SecurityError: Failed to execute 'setTimeout' on 'Window': Blocked a frame with origin "http://localhost:1402" from accessing a frame with origin "http://localhost:1401". Protocols, domains, and ports must match.

emit	@	hammerhead.js:11221
onBodyContentChanged	@	hammerhead.js:7649
(anonymous function)	@	hammerhead.js:1914

```

### PR DESCRIPTION
**Pull request by miherlosev**
@AlexanderMoskovkin @churkin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by miherlosev** [comment]
ping @churkin

**Comment by churkin** [comment]
lgtm

**Pull request merged**
