### PR TITLE
Hammerhead initialization fails in IE after document.write (close #525)

### LINKED ISSUE #525: Hammerhead initialization fails in IE after document.write
A `cannot execute code from freed script` exception is raised when evaluating task script in iframe, after `document.write` was called. Also bad thing is that the error is silently swallowed, because it is thrown on [RUN_TASK_SCRIPT event](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/iframe.js#L94), and event emitter just ignores `freed script` errors (https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/event-emitter.js#L23). 

When `document.write` is called, `hammerhead` reattaches existing sandbox, including ShadowUI. When ShadowUI attaches to DOM, it replace some methods in HTMLBodyElement and HeadHTMLElement prototypes. After that iframe is initialized through `_raiseReadyToInitEvent`, and evaluate task script. When it does that, it calls UrlResolver.updateBase, that uses `document.head.getElementsByTagName` method(https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/url-resolver.js#L61), previously overriden by ShadowUI at `document.write`. So it raises a `freed script` error here.

### PR DESCRIPTION
**Pull request by churkin**
\сс @AndreyBelym @LavrovArtem

### CODE REVIEW

**Comment by LavrovArtem** [comment]
What about tests?

**Comment by AndreyBelym** [comment]
It's hard to write a test for it. This bug reproduces very frequently on a lot of ASP tests on farm in automatic mode, but very rarely on my machine or on farm in manual mode. Likely it depends on internal IE's conditions by which it will make script freed or not.

**Comment by AndreyBelym** [comment]
lgtm, tested on farm.

**Comment by churkin** [comment]
@AndreyBelym excellent!

**Comment by miherlosev** [comment]
lgtm

**Pull request merged**
