### PR TITLE
Disable strict mode for Babel transform (closes #344)

### LINKED ISSUE #344: Blacklist 'useStrict' in Babel
Strict mode disallows usage of `callee.caller`. So if a function traverses call stack with `callee.caller`, and TestCafe functions are strict-mode functions, an exception will be thrown. Unfortunately, we have  that nasty kind of a function in DevExpress ASP.Net controls, so we need to disable strict mode in Babel transform options.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
Needs regression test \r-

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
