### PR TITLE
update ios to latest version (9.2)

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
@AlexanderMoskovkin 
Tests for ios 9.2 don't start.

I perform the test run using sc-tunnel sucessfully.
ios_9_2_run

Please, investigate the problem.

**Comment by AlexanderMoskovkin** [comment]
ok

**Comment by AlexanderMoskovkin** [comment]
FYI: we've found an issue on saucelabs with ios 9.2 vm. We'll write to their support team

**Comment by miherlosev** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
