### PR TITLE
small refactoring

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem 
Changes:
- move string const '%hammerhead%' to the internal-properties.js
- refactor `domProcessor.TARGET_ATTR_TAGS`

### CODE REVIEW

**Comment by LavrovArtem** [comment]
lgtm

**Comment by miherlosev** [comment]
Mark `DomProcessor.isTagWithTargetAttr method` method as `static`.

**Comment by LavrovArtem** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
