### PR TITLE
fix 'Font doesn't load in http://bxt-to-wc-weu-tst.azurewebsites.net/ site' (close #900)

### LINKED ISSUE #900: Font doesn't load in http://bxt-to-wc-weu-tst.azurewebsites.net/ site
Console

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
There is a problem with module `iltorb` on Travis CI machine.
I created issue https://github.com/mayhemydg/iltorb.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@churkin @LavrovArtem
Review again, please

**Comment by churkin** [comment]
lgtm

**Pull request merged**
