### PR TITLE
remove write, writeln from MethodCallInstrumentation (close #382, #409, #411)

### LINKED ISSUE #382: MethodCallInstrumentation - move code to overriden methods
We have a `methodCallInstrumentation` for methods which are already overriden.
For example:
`querySelector`,
`querySelectorAll`,
`write`
`writeln`

We can to move code from `methodCallInstrumentation` to appropriate overriden methods.
After it will be done `methodCallInstrumentation` will contain the code only for `postMessage`.
If we can override `postMessage` then we can to delete `methodCallInstrumentation`.

/cc @churkin @inikulin

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @LavrovArtem 
@MargaritaLoseva check test name

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Comment by MargaritaLoseva** [comment]
lgtm

**Pull request merged**
