### PR TITLE
Update the Acorn parser (close #320)

### LINKED ISSUE #320: Regression: JSON parse errors in HHM
Guys, please take a look @churkin @LavrovArtem @miherlosev 
Seems like it's one of these commits: https://testcafe-hhhm.devexpress.com/history?timestamp=1449082979570&siteUrl=http://www.tripadvisor.com/

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @inikulin @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
Can we just take acorn `src`? (https://github.com/ternjs/acorn/blob/master/src) and clean up unnecessary things there?

**Comment by inikulin** [comment]
\r-

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@inikulin no, because there are have duplicate variable declarations between files and take the source code from [dist](https://github.com/ternjs/acorn/tree/master/dist) easier

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Pull request merged**
