### PR TITLE
fix `Hammerhead internal event listener is called twice` (close #2062)

### LINKED ISSUE #2062: Hammerhead internal event listener is called twice
### What is your Test Scenario?
Record a test with the TestCafe Studio. See https://github.com/DevExpress/testcafe-studio/issues/2541
 
### What is the Current behavior?
Internal event listener may be called twice
 
### What is the Expected behavior?
It should be called once
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

```
fixture `test`
    .page `about:blank`;

test('test', async t => {
    await t.eval(() => {        
        window.counter = 0;
        window['%hammerhead%'].eventSandbox.listeners.addInternalEventListener(window, ["keypress"], () => { 
            window.counter++;
        });
        var ev = new Event('keypress');
        ev.key = 'a';
        window.dispatchEvent(ev);
    });
    await t.wait(1000);
    console.log(await t.eval(() => window.counter));    
});
```

</details>

### Steps to Reproduce:
Another way to determine this issue:

1. Set a huge t.wait() timeout in the test above
2. Run test, open chrome DevTools
3. Check the event handlers via console: getEventListeners(window).keypress
4. There will be two same handlers

### Your Environment details:
 
* testcafe version: 1.2.1  
* node.js version:  10.15.1
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 75, Opera 62
* platform and version:          Windows 10, Linux Ubuntu 18.04

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by kirovboris** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Pull request merged**
