### PR TITLE
add test case for parens in nullish coalescing

### PR DESCRIPTION
**Pull request by P4**
## Purpose
Test case for parentheses in logical expressions involving `??` and `&&`, as [requested](https://github.com/DevExpress/esotope-hammerhead/pull/19#issuecomment-1358788868) by @miherlosev 

## References

- DevExpress/esotope-hammerhead#19 
- [SyntaxError: cannot use `??` unparenthesized within `||` and `&&` expressions - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_use_nullish_coalescing_unparenthesized)

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by miherlosev** [comment]
Please, fix [build errors](https://github.com/DevExpress/testcafe-hammerhead/actions/runs/3746531236/jobs/6361946720).

**Comment by P4** [comment]
Note that the added test will fail, since the actual fix is in DevExpress/esotope-hammerhead#19, which needs to get merged an released first. 

Might be a good idea to give that library its own test suite

**Comment by miherlosev** [comment]
Thank you for your work.

However, it's necessary to do a few more things:
* create a custom `esotope-hammerhead` build based on the [PR](https://github.com/DevExpress/esotope-hammerhead/pull/19)
* attach it to this PR and update the package.json file as follows:
```js
{
   "esotope-hammerhead: esotope-hammerhead-0.6.2.tgz,
}
```

The main idea is to test the changes from the `esotope-hammerhead` PR with the whole `testcafe-hammerhead` test site.

**Review by Aleksey28 — CHANGES_REQUESTED** [review]
Please update `esotope-hammerhead` to 0.6.3

**Review by Aleksey28 — APPROVED** [review]

**Pull request merged**
