### PR TITLE
fix `Update babel-preset-env target to node 6` (part of #1651)

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1651

### Changes
1. Update Node to 6 version.
2. Remove unnecessary `targets.browsers` from `src/client/.babelrc`.

### References
https://github.com/DevExpress/testcafe-hammerhead/pull/1265#issuecomment-333855141

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Pull request merged**
