### PR TITLE
fix 'Hammerhead doesn't process 'svg' element and it child nodes' (close #614)

### LINKED ISSUE #614: Hammerhead doesn't process 'svg' element and it child nodes.
It's reproduced in the playground:

1) open next page in the playground.
```html
<!DOCTYPE html>
<html>
<body>
<h1>SVG example</h1>
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
</body>
</html> 
```
2) evaluate next expressions in the console:
`document.getElementsByTagName('h1')[0].dispatchEvent.toString() //returns overriden function` 
`document.getElementsByTagName('svg')[0].dispatchEvent.toString() //returns original function` 
`document.getElementsByTagName('circle')[0].dispatchEvent.toString() //returns original function`

### PR DESCRIPTION
**Pull request by miherlosev**
@inikulin @georgiy-abbasov

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by miherlosev** [comment]
don't merge. I will to perform an additional investigation.

**Comment by miherlosev** [comment]
> I will to perform an additional investigation.

Done.

Test was updated.
Test name was checked by @MargaritaLoseva .
Review again, please. @georgiy-abbasov @inikulin

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by miherlosev** [comment]
ping @inikulin

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
