### PR TITLE
support the `target` attribute of base tag in multiple-windows mode (#5393 in TestCafe)

### PR DESCRIPTION
**Pull request by AlexKamaev**
for https://github.com/DevExpress/testcafe/issues/5393

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Review by miherlosev — APPROVED** [review]

**Review by LavrovArtem — APPROVED** [review]

**Pull request merged**
