### PR TITLE
Abort XHRs after 2 minutes (closes #404)

### LINKED ISSUE #404: Timeout of 60s for XHRs is still too small sometimes
Sometimes we are aborting long-polling XHR on [GridViewDemos](https://demos.devexpress.com/ASPxGridViewDemos/DataBinding/LargeDatabase.aspx), that waits while server creates a large database. Speed of the process depends on VM performance on farm, so sometimes server doesn't finish database creation in 60s.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @churkin

### CODE REVIEW

**Comment by miherlosev** [comment]
Waiting for #277

**Comment by miherlosev** [comment]
@AndreyBelym rebase and retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
FPR. `timeout` test in `sandbox/event/message-test.js` is unstable because of low performance of iOS emulator on Mac VMs. Maybe it's good idea to increase the [timeout value](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/event/message-test.js#L265) in test.

**Comment by churkin** [comment]
@AndreyBelym I have created #410 issue

**Comment by churkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
\ping @inikulin

**Comment by inikulin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
thanks

**Pull request merged**
