### PR TITLE
fix 'Error raised in beforeunload dialog handler in hammerhead' (close #698)

### LINKED ISSUE #698: Error raised in beforeunload dialog handler in hammerhead
This problem make tests failed in https://github.com/DevExpress/testcafe/pull/675
So please fix it ASAP if it possible

It reproduces only on SauceLab virtual machines: 
`platform:    'OS X 10.11',
browserName: 'safari',
version:     '9.0'`
There isn't this problem on our Mac (OS 10.11.5 safari 9.1.1)
Error raised in _onBeforeUnloadHandler method: `Properties can only be defined on Objects`
Page for reproduce in hammerhead-playground:
index.html
```
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1">
    <title>FEATURES</title>
</head>
<body>
<iframe src="foriFrame.html"></iframe>
</body>
</html>
```
foriFrame.html
```
<!DOCTYPE HTML>
<html>
<head>
    <title>IFRAME IFRAME IFRAME</title>
</head>
<body style="height: 250px;">
    <button id="reload">reload</button>
<script>
    window.onbeforeunload = function (e) {
        return 'BU!';
    };

    document.getElementById('reload').addEventListener('click', function () {
        document.location.reload();
    });
</script>
</body>
</html>
```
I added creation new element in window.top to see raised error (in onerror method in HH), it can be something like this:
```
var div = window.top.document.createElement('div');

div.textContent = msg;
window.top.document.body.appendChild(div);
```

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
lgtm

**Comment by LavrovArtem** [comment]
ping @churkin

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Pull request merged**
