### PR TITLE
fix 'Script error after setting relative url value to the "base" tag s href attribute' (close #422)

### LINKED ISSUE #422: Script error after setting relative url value to the "base" tag's href attribute

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
ping @churkin @LavrovArtem

**Comment by LavrovArtem** [comment]
lgtm

**Comment by miherlosev** [comment]
@AlexanderMoskovkin  review, please

**Comment by AlexanderMoskovkin** [comment]
lgtm
@VasilyStrelyaev please, check test names

**Comment by miherlosev** [comment]
@AlexanderMoskovkin all test names for new tests was checked by @MargaritaLoseva

**Comment by AlexanderMoskovkin** [comment]
great!

**Pull request merged**
