### PR TITLE
switch to latest iOS and MS EDGE browser versions

### PR DESCRIPTION
**Pull request by miherlosev**
@kirovboris @LavrovArtem

### CODE REVIEW

**Comment by kirovboris** [comment]
lgtm

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR.
Saucelabs doesn't allow to specify the latest iOS version by removing the `version` field.
So, I change only MS Edge.

**Comment by kirovboris** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
