### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Review by Farfurix — APPROVED** [review]

**Comment by LavrovArtem** [comment]
Before:
image

After:
image

**Comment by LavrovArtem** [comment]
Before:
image

After:
image

**Comment by LavrovArtem** [comment]
Before:
image

After:
image

**Comment by LavrovArtem** [comment]
https://github.com/DevExpress/acorn-hammerhead/pull/5

Before:
image

After:
image

**Comment by LavrovArtem** [comment]
https://github.com/DevExpress/testcafe/issues/6297

**Comment by LavrovArtem** [comment]
| Commit | Execution count | Before  | After |
|:------------- |:------------- |:---------------:| :-------------:|
| getFirstDestUrl improvement | 200 000 | ~10s | ~4.9s |
| parseUrl improvement | 500 000 | 9.5s | 2s |
| beforeTransform improvement | 20 000 | ~14.5s | ~4.7s |
| acorn improvement | 500 000 | ~8s | ~4s |

**Review by miherlosev — APPROVED** [review]
Excellent

**Review by Farfurix — APPROVED** [review]

**Pull request merged**
