### PR TITLE
Bump version to 10.6.5

### PR DESCRIPTION
**Pull request by churkin**
@helen-dikareva

### CODE REVIEW

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
We need to add timeout for selectors in tests for `Roles` with iframes. [Like here.](https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/api/es-next/iframe-switching/test.js#L8)
I think we can merge it now.

**Pull request merged**
