### PR TITLE
remove querySelector, querySelectorAll from MethodCallIntrumentation

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @AndreyBelym 
partial fix for #382

### CODE REVIEW

**Comment by AndreyBelym** [comment]
lgtm

**Comment by miherlosev** [comment]
ping @churkin

**Comment by churkin** [comment]
\r-

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Pull request merged**
