### PR TITLE
fix lint errors

### PR DESCRIPTION
**Pull request by churkin**
\сс @AlexanderMoskovkin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
ping @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
what about https://github.com/DevExpress/testcafe-hammerhead/pull/883/files#diff-4d2f4dd3abdd4b3b33454100af430ebdR437 ? Will it be fixed in a separate PR?

**Comment by churkin** [comment]
@AlexanderMoskovkin yes

**Pull request merged**
