### PR TITLE
fix wrong Browser.isWebKit calculation for Safari

### PR DESCRIPTION
**Pull request by miherlosev**
@inikulin @AlexanderMoskovkin @churkin 
for more details see https://github.com/DevExpress/testcafe/issues/113

### CODE REVIEW

**Comment by inikulin** [comment]
So, have you figured out why this change was introduced? Is there something in Hammerhead what we can potentially break?

**Comment by miherlosev** [comment]
I am investigating it

**Comment by miherlosev** [comment]
waiting for merge https://github.com/DevExpress/testcafe-hammerhead/pull/267 pull request

**Comment by inikulin** [comment]
@miherlosev What do you mean? This one is the #267

**Comment by miherlosev** [comment]
This pull request opens the problem that fixed in #267

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by miherlosev** [comment]
I have created the separate issue #301 to support the scenatio  - "restoring shadowUI stylesheets after `document.write` in iframe" for all browsers (not only for WebKit).

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
