### PR TITLE
fix "`navigateTo` doesn't work if current location is `about:blank`" (close #645)

### LINKED ISSUE #645: `navigateTo` doesn't work if current location is `about:blank`
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/index.js#L156

### PR DESCRIPTION
**Pull request by miherlosev**
@inikulin @churkin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
we have some troubles with firefox on saucelabs after it was updated there. @georgiy-abbasov is working on this

**Comment by inikulin** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
@miherlosev, yesterday was released a new version of selenium which supports Firefox 47, so Sauce Labs provides this version by default for now. Unfortunately, it has an error - we cannot get properties of global objects (for example `window.global_test_results`), while publishing test results via qunit-harness. At the current moment we have only one way to keep test process stable - we should specify firefox version - 46. Make next corrections in this PR, please.
```js
{
        platform:    'Windows 10',
        browserName: 'firefox',
        version: '46'
}
```
and
```js
{
        browserName: 'firefox',
        platform:    'OS X 10.11',
        version:      '46'
}
```

**Comment by miherlosev** [comment]
Ok. I will do this in the separate pull request.

**Comment by inikulin** [comment]
@georgiy-abbasov 
> @miherlosev, yesterday was released a new version of selenium which supports Firefox 47, so Sauce Labs provides this version by default for now. Unfortunately, it has an error - we cannot get properties of global objects (for example window.global_test_results

What does this mean, can you elaborate? We use such properties both in testcafe and hammerhead client. Does it mean they don't work in Firefox 47?

**Comment by georgiy-abbasov** [comment]
@inikulin, yes, it is.

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
Need to do:
1)set proxy url for `iframes` and `images` for special pages(`about:blank`, `about:error`).
2)in `hammerhead.navigateTo` use `parseProxyUrl.destUrl`.

**Comment by miherlosev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
