### PR TITLE
Build in release configuration by default, unless --dev flag is not specified (closes #257)

### LINKED ISSUE #257: Create 'dev' build option
By default we should build and run tests in release configuration, unless `--dev` flag is not specified.

### PR DESCRIPTION
**Pull request by inikulin**
\cc @churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
if the `release` configuration is default maybe we should remove the `--release` flag in the [package.json](https://github.com/DevExpress/testcafe-hammerhead/blob/master/package.json#L63)?

**Comment by inikulin** [comment]
@AlexanderMoskovkin good catch, thank you

**Comment by inikulin** [comment]
FPR

**Comment by inikulin** [comment]
**update:** removed unnecessary source maps stub from client code

**Comment by inikulin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
ping @churkin

**Comment by churkin** [comment]
lgtm

**Pull request merged**
