### PR TITLE
fix `Out of memory crash` (close #1546)

### LINKED ISSUE #1546: Out of memory crash
For reproducing this problem need to call some `console` function (for example `error`) from a same-domain iframe and pass an object with circular structure as argument to this function.

https://github.com/DevExpress/testcafe-hammerhead/blob/510ba1f8c21c4369aad67ccb459e6f0a7f48c6ac/src/client/sandbox/event/message.js#L206-L207
image

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
After this PR we need to change the next function in testcafe repo:

https://github.com/DevExpress/testcafe/blob/c2093de49212a9c0bd1effc0f6c36e81735b601d/src/client/driver/driver.js#L175-L193

to:

```js
    _onConsoleMessage ({meth, line}) {
        this.consoleMessages = this.consoleMessages.addMessage(meth, line);
    }
```

**Comment by AndreyBelym** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot retest-force

**Comment by AndreyBelym** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
The `appveyor` tests shouldn't pass because this PR has breaking changes.

**Pull request merged**
