### PR TITLE
fix webmake for 0.10 node

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin 
The same thing as as in https://github.com/DevExpress/testcafe/pull/1334

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by miherlosev** [comment]
FRP

**Pull request merged**
